# -*- coding: utf-8 -*-
# © 2015 Eficent Business and IT Consulting Services S.L.
# - Jordi Ballester Alomar
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).

{
    'name' : 'AO Profile',
    'version' : '1.0.0',
    'depends' : [
        'point_of_sale',
        'account_voucher',
        'project',
        'note',
        'project_issue',
        'account_accountant',
        'sale',
        'stock',
        'mrp',
        'purchase',
        'hr',
        'hr_timesheet',
        'hr_timesheet_sheet',
        'hr_holidays',
        'hr_expense',
        'hr_evaluation',
        'account_asset',
        'smile_decimal_precision',
        'hr_payroll',
        'account',
        'account_analytic_analysis',
        'account_analytic_default',
        'account_analytic_plans',
        'account_anglo_saxon',
        'account_bank_statement_extensions',
        'account_budget',
        'account_cancel',
        'account_chart',
        'account_check_writing',
        'account_followup',
        'account_fstr',
        'account_payment',
        'analytic',
        'analytic_user_function',
        'auth_crypt',
        'base_report_designer',
        'claim_from_delivery',
        'crm_claim',
        'crm_helpdesk',
        'crm_profiling',
        'decimal_precision',
        'delivery',
        'document',
        'edi',
        'email_template',
        'fetchmail',
        'hr_attendance',
        'hr_contract',
        'hr_payroll_account',
        'hr_timesheet_invoice',
        'knowledge',
        'lunch',
        'marketing',
        'mrp_byproduct',
        'mrp_operations',
        'mrp_repair',
        'partner_aging',
        'procurement',
        'product',
        'product_manufacturer',
        'project_issue_sheet',
        'purchase_double_validation',
        'purchase_requisition',
        'report_webkit',
        'sale_crm',
        'sale_journal',
        'sale_margin',
        'sale_mrp',
        'sale_order_dates',
        'sale_stock',
        'subscription',
        'survey',
        'ursa_crmlead',
        'ursa_helpdesk',
        'ursa_product_customizations',
        'ursa_product_gtin',
        'ursa_product_reference',
        'ursa_ref_partner',
        'ursa_sale_customizations',
        'ursa_shipwire',
        'ursa_web_style',
        'purchase_location_by_line'
    ],
    'author' : 'Eficent Business and IT Consulting Services S.L.',
    'summary': 'Contains the modules used by AO',
    'website' : 'http://www.eficent.com',
    "category": 'Customizations',
    'active': False,
    'installable': True,
}
